# Generated by Django 3.2.8 on 2021-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_answer',
            field=models.ManyToManyField(to='pollApp.Choice'),
        ),
    ]
